[mypy]
python_version = 3.7
mypy_path = bfs_executor/src
warn_unused_configs = True
warn_return_any = True
warn_redundant_casts = True
warn_unused_ignores = True
disallow_untyped_defs = True
disallow_incomplete_defs = True
no_implicit_optional = True
check_untyped_defs = True
show_error_codes = True
pretty = True
exclude = (?x)(^venv/|^\.venv/|^build/|^dist/|^\.mypy_cache/)

# Be more permissive in tests
[mypy-bfs_executor.tests.*]
disallow_untyped_defs = False
